spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaplicaciondb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ms_user
    password: ms_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
